baseurl      = "https://gogo2464.github.io/gogo-s-blog-cpe"
title        = "CPE Blog"
languageCode = "en-us"
theme        = "hello-4s3ti"
paginate     = 10

[params]
  defaultTheme = "dark"
  EnableThemeToggle = true
  EnableSharingButtons = true
  EnableGlobalLanguageMenu = true
  backgroundImage = "static/menu/hacker.png"
  backgroundEffects = true
  showPosts = true
  tags = true
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  logo = { logoText = "coolapso.sh", logoCursorColor = "#ffffff" }
  footer = { showVersion = true, socialIcons = true, author = true, rss = true, trademark = true, copyright = true, bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>", "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>"] }


  # Subtitle for home
  homeSubtitle = "The official CPE blog (from gogo) to expose common cyber security projects."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

#[taxonomies]
#    category = "blog"
#    tag      = "tags"
#    series   = "series"

[languages]
  [languages.en]
    title = "Hello Friend NG"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
    [languages.en.params]
	  keywords = ""
	  readOtherPosts = "Read other posts"
	  [languages.en.params.logo]
        logoText = "crypto pwn elite (cpe) blog"
        logoHomeLink = "/gogo-s-blog-cpe"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "putting-games-on-darknet"
    name       = "Putting-games-on-darknet"
    url        = "/putting-games-on-darknet"
	
  [[menu.main]]
    identifier = "0toOverflow"
    name       = "0toOverflow"
    url        = "/from-0-to-buffer-overflow-by-projects"
	
  [[menu.main]]
    identifier = "exploit-dev"
    name       = "exploit-dev"
    url        = "/exploit-dev"
	
  [[menu.main]]
    identifier = "game-hacking-for-speedrun"
    name       = "game-hacking-for-speedrun"
    url        = "/game-hacking-for-speedrun"