baseurl      = "https://gogo2464.github.io/gogo-s-blog-cpe"
title        = "CPE Blog"
languageCode = "en-us"
theme        = "hello-4s3ti"
paginate     = 10

[params]
  defaultTheme = "dark"
  EnableThemeToggle = true
  EnableSharingButtons = true
  EnableGlobalLanguageMenu = true
  backgroundImage = "static/menu/hacker.png"
  backgroundEffects = true
  showPosts = true
  tags = true
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  logo = { logoText = "coolapso.sh", logoCursorColor = "#ffffff" }
  footer = { showVersion = true, socialIcons = true, author = true, rss = true, trademark = true, copyright = true, bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>", "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>"] }


  # Subtitle for home
  homeSubtitle = "The official CPE free educational books for auditing cyber security issues only by practicing on real environment. CPE: the Cryptography and PWN elites that will send you to the CPE!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

#[taxonomies]
#    category = "blog"
#    tag      = "tags"
#    series   = "series"

[languages]
  [languages.en]
    title = "CPE"
    subtitle = "CPE: the school that schools to send you to cpe!"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "crypto pwn elite (cpe) blog"
      logoHomeLink = "/gogo-s-blog-cpe"

  [[menu.main]]
    identifier = "0toCrypto"
    name       = "Crypto"
    url        = "/from-0-to-crypto-by-projects"
	weight     = 1

  [[menu.main]]
    identifier = "0toOverflow"
    name       = "Pwn"
    url        = "/from-0-to-buffer-overflow-by-projects"
	weight     = 2
	
  [[menu.main]]
    identifier = "Putting-games-on-darknet"
    name       = "Elite"
    url        = "/putting-games-on-darknet"
	weight     = 3
